name: proyecto_formativo
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  camera:
  path_provider:
  path:
  flutter:
    sdk: flutter
  http: ^1.1.0
  flutter_map: ^5.0.0
  geolocator: ^10.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
